### ISSUE TITLE
more basic programs

### ISSUE THREAD

**Issue by horerick46** [RajkumarSony/HacktoberFest2022#25]
@RajkumarSony sir, can I add more basic programs to the folder.

**Comment by nitishgiri007** [comment]
Hello sir please help me to become a contributor by providing this repo

**Comment by Nikhil-2002** [comment]
hello sir plz assign more tasks

**Comment by geetika001** [comment]
@RajkumarSony Can I please add some basic programs in this repo ubder Hacktoberfest.I'll be adding basic programs for 3 languages as C++,Java and Python

**Comment by RajkumarSony** [comment]
No sorry, Only projects will be acceptable. Thank You.
