### ISSUE TITLE
want to contribute some c++ programs

### ISSUE THREAD

**Issue by amansgith** [RajkumarSony/HacktoberFest2022#3]
hii i want to contribute to your repository but i can't find any program folders..
do i have to create some folders to add programs?
also i your repo accepted by hacktoberfest because i contributed to one such repo and later i found that hacktober fest has excluded their repo from the event.

**Comment by RajkumarSony** [comment]
I have already created a few folders. Please check once again.

**Comment by amansgith** [comment]
ok yeah! now i am able to see folders

**Comment by RajkumarSony** [comment]
Great!!
